apiVersion: v2
name: aws-eks-asg-rolling-update-handler
version: 1.6.0
description: Handles rolling upgrades for AWS ASGs for EKS by replacing outdated nodes by new nodes.
home: https://github.com/TwiN/aws-eks-asg-rolling-update-handler
maintainers:
  - name: TwiN
