apiVersion: v2
name: gatus
description: Automated service health dashboard
icon: https://raw.githubusercontent.com/TwiN/gatus/a1c8422c2ff2b9d0a6f184c99e4dc728d3f2cd75/web/static/logo-192x192.png
version: 1.5.0
appVersion: v5.23.2
type: application
engine: gotpl
home: https://github.com/TwiN/gatus
sources:
  - https://github.com/TwiN/helm-charts
  - https://github.com/TwiN/gatus
maintainers:
  - name: TwiN
keywords: ['gatus', 'healthcheck', 'uptime', 'monitoring']
